name: 'Setup Quasar'
description: 'Set up your GitHub Actions workflow with Cordova/Quasar environment. Only supports macos & ubuntu at this time.'
author: 'joshstrange'
branding:
  color: purple
  icon: code

inputs:
  cordova-version:
    description: Version range or exact version of Cordova to use
    default: '9'
  quasar-version:
    description: Version range or exact version of Quasar to use
  install-java:
    description: Whether to install Java
    default: true
  install-pods:
    description: Whether to install CocoaPods
    default: true

runs:
  using: 'node12'
  main: 'lib/main.js'
